version: '2.0'

services:
  etcd:
    image: nginx
    container_name: nginx-lb
    hostname: nginx-lb
    volumes:
    - /root/kubeadm-multimaster/nginx-lb/nginx-lb.conf:/etc/nginx/nginx.conf
    ports:
    - 16443:16443
    restart: always
